
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: first-push-web
  labels:
    app.kubernetes.io/name: first-push
    app.kubernetes.io/component: web
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 20%
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: first-push
      app.kubernetes.io/component: web
  template:
    metadata:
      name: first-push-web
      labels:
        app.kubernetes.io/name: first-push
        app.kubernetes.io/component: web
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: first-push
      containers:
      - name: first-push-web
        image: "image-registry.openshift-image-registry.svc:5000/first-push-web:latest"
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
          - |
            $HOME/boot.sh
        ports:
          - containerPort: 8080
            protocol: TCP
        env:
          - name: PORT
            value: "8080"
        livenessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "ps -ef | grep 'boot.sh' | grep -v grep"
