
---
kind: Service
apiVersion: v1
metadata:
  name: sep9-app-web
  labels:
    app.kubernetes.io/name: sep9-app
    app.kubernetes.io/component: web
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    targetPort: 8080
  selector:
    matchLabels:
      app.kubernetes.io/name: sep9-app
      app.kubernetes.io/component: web
