
---
kind: Service
apiVersion: v1
metadata:
  name: hello-spring-cloud-web
  labels:
    app.kubernetes.io/name: hello-spring-cloud
    app.kubernetes.io/component: web
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-spring-cloud
    app.kubernetes.io/component: web
