
---
kind: Service
apiVersion: v1
metadata:
  name: sep8-app-web
  labels:
    app.kubernetes.io/name: sep8-app
    app.kubernetes.io/component: web
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: sep8-app
    app.kubernetes.io/component: web
