
---
kind: Service
apiVersion: v1
metadata:
  name: first-push-web
  labels:
    app.kubernetes.io/name: first-push
    app.kubernetes.io/component: web
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: first-push
    app.kubernetes.io/component: web
